### ISSUE TITLE
Add player sprite from Tyler

### ISSUE THREAD

**Issue by flip40** [DemoProductions/shmup#104]
Tyler made a player sprite, I think we should add it asap, because group made art is best art.

**Comment by ghost** [comment]
That is a nice looking player sprite

32x32
![868d4352-4ab5-11e6-801a-3c52c93c9d77](https://cloud.githubusercontent.com/assets/10818718/16937076/d530ae46-4d20-11e6-9a11-c4ad75bf5028.png)

**Comment by ghost** [comment]
Hold off on this until the 64x64 version of this sprite?

**Comment by flip40** [comment]
I say we add the 32x32. It will give us a feel for the size and how it looks / feels to play with that size. I think it is a bit small for a hitbox, but being able to test it is far better than just relying on my intuition. Also it should be easy to replace with the 64x64 when it is ready.

**Comment by stannardtyler** [comment]
hey thanks! yea fast prototype early, and we can add on or expand sizes later, the art doesnt take too much time, I jus need to be whipped since i work and play games all the time lol. If want I'll make a 64x64 variant as well to see which we prefer in game. Bigger the size the more time into the art, but the cooler it looks!
