### ISSUE TITLE
Add GUI draw for player spawn location in LevelControllerEditor

### ISSUE THREAD

**Issue by flip40** [DemoProductions/shmup#109]
GUI Draw, and preferably also a transform handle so it can be easily moved and adjusted visibly.

Could copy / paste the code that does this for WaveEditor, just need to adjust the property the transform is for, I think. Can consider whether or not to have the snap functionality as well, but part of me fears cluttering the editor too much (so useful though too).

**Comment by ghost** [comment]
Since player spawn locations can vary in levels, would need some way to determine which level the user is editing player spawn for. Starting to think that player spawn should be set to a certain location to keep things simple in the level editor. Also can't think of too many cases where having a varied player spawn would make things more fun in a shmup since the player can move around the screen fast. Do you think that I should change player spawn to be global in all levels instead of by level?

**Comment by flip40** [comment]
I agree. Other than how it might look when spawning (if you wanted them to appear in a certain location), there is no gameplay benefit to spawn locations unique to each level. Removing it, at least for now, would make it less confusing. We can worry later about modifying it if we find we really want to do that.
