### ISSUE TITLE
Vertical scrolling or horizontal scrolling?

### ISSUE THREAD

**Issue by flip40** [DemoProductions/shmup#12]
I initially wanted to do vertical scrolling, but I realized that it might not be such a good idea. The reason arcade games did vertical scrolling was because most arcade systems used a tall screen. Most computers (read ALL computers) use a near square at worst and a wide screen at best. As such does this make sense to make the game a horizontal scroller instead? My only problem with this is do we stick with top down in this case, or should we do a side view instead?

The thought is that with wide screen, doing a vertical scroller will give us perhaps too much horizontal motion while leaving far less room for enemies to be on the screen as they come down to you. This would be reversed if we go horizontal, as enemies can be on the screen longer, and we also restrict player movement to dodge (having too much room makes it too easy to dodge shots).

What do you guys think?

Example of arcade top view and vertical:
![batsugun_02](https://cloud.githubusercontent.com/assets/10754057/13058811/80877844-d3da-11e5-84a8-f1636f4191d2.png)

Example of side view and horizontal:
![ss-aegis-wing-002](https://cloud.githubusercontent.com/assets/10754057/13058815/8c5b4dbc-d3da-11e5-860a-bcf7d3f8d080.png)

Don't have any example of top view and horizontal, but no reason we can't go for that if we think it will work. I would generally argue that the brain prefers horizontal as a side view and vertical as a top view, but there is no reason we can't just ignore that. Also no reason we can't just do a vertical despite the wide screen (perhaps we just restrict the game to a more square or portrait size, or just deal with the width/length difference).

**Comment by ghost** [comment]
I prefer vertical scrolling (the game could play in a vertically shaped windowed screen), think it is easier to see things coming at you especially if there is a ton of stuff on the screen. But I am fine with trying horizontal scrolling. May depend on the kind of game we want

**Comment by flip40** [comment]
Last I recall of the discussion is that I feel horizontal makes the best use of wide screen monitors (while keeping the narrow "corridor" shape). On the other hand, I don't like the side view of ships, I am a fan of wings and your ships definitely have those. As Adrian pointed out, we could just not use the entire width of the monitor and just have a vertically shaped window. We could perhaps find other uses for the extra screen space while keeping the same feel of a corridor.

Another thought I had ~~that I swear I made a write up on at some point (I can't seem to find it),~~ is that we could perhaps just do a slightly different game.

We are still early enough where we could change a bit and go for some sort of "Descent" style game, randomly generate levels but make it more of a 1 life exploration rogue-like game. Not sure that kind of game would run well with multiple players, but maybe we could make it work (or just not have multiple players in that case).

Not to throw our game plan out the window or anything, just throwing out an idea that occurred to me with what kind of game we could shoot for if we allowed full player control instead of scrolling, and it would solve any debate on the screen direction.

This is a similar idea to what I described here, although unlike the 2d version we would end up with, this is truly a 3d and 6 degrees of freedom game in the style of Descent: http://store.steampowered.com/app/327880/

**Comment by ghost** [comment]
Lets stick to a shmup for now to keep things simple and make sure we have a more complete game. What do you think Tyler and Jamahl? Do you prefer a horizontal or a vertical shmup? I don't mind the side view of ships myself and after watching the lightening game mentioned I actually prefer horizontal (unless we have a game like Touhou where there is an overwhelming amount of things on the screen, enough so that a vertical view saves the eye a bunch of trouble).

The "Descent" style game mentioned looks really fun though. Maybe a future project? :)

**Comment by stannardtyler** [comment]
tbh i enjoy horizontal since it adds more art and depth of field to the game, but as this being a simple first time go and with one of us for now, me, would be taking on the art role, unless someones feels comfortable to do like backgrounds and stuff we can go there. I actually had my computer out of commission for about a week and finally got it back today. Im kinda tied between like a pixelized shooter that is inspired by geometry wars where we have like a grid like background with bright and colorful simple enemies to shoot with. Maybe with the simple art we can tie in some interesting mechanices to spice it up. And no i dont wana make a geometry wars copy but something along the lines of that but maybe simpler effects and a different approach. These coming weeks I'll try to get some concepts goin out to give us a feel, 3 concepts to choose from!

**Comment by flip40** [comment]
I think we sound agreed on horizontal then. Any of the artistic styles you mentioned sound good to me, will be interesting to see what we come up with. I would be willing to try and help out with the background art, though it depends a bit on the style we go for.

Anyways, horizontal it is, I think, unless we hit some issues with not being able to get background art in or whatever. At least due to the design we should be able to pretty easily swap it over to vertical.
