### ISSUE TITLE
Remove some bad commits I added without code review

### ISSUE THREAD

**Issue by ghost** [DemoProductions/shmup#138]
Should have left these on a separate branch, mostly the ones relating to boss ai. May be easier to delete all commits until the commit with the message 'waves instantiated in the foreground'. Also might want to keep an issue open for the player spawn position editor, I believe that feature uses the LevelController component transform or something like that

**Comment by flip40** [comment]
I'll move these to another branch then revert changes on master if you would like. Assuming you want the old code commits to perhaps build on for the AI later?

**Comment by flip40** [comment]
How bad are the commits? Do they significantly break anything? If not, lets just leave them and have an issue open to improve, rewrite, or bug fix where necessary. Unless just everything is broke and it isn't worth the effort to just patch the mistakes.

**Comment by ghost** [comment]
Recent commits didn't actually break anything, but they probably shouldn't be in the master branch.  Should have maybe taken advantage of the state machine relating to Unity animations. I think we had already discussed using that for boss AI at some point?

With boss AI, I tried to move in a vertical line going up and down but sometimes pausing. And I also tried to give the boss some variations in shoot patterns like 'two bullets at a time' or 'two bullets in different directions at a time' or 'boss spinning and shooting some type of bullet'. 

Lets keep those commits for now then and then either remove the 'TestBossAI' and 'TestBoss' scripts or update them. The Timer script should be useful though

**Comment by flip40** [comment]
Honestly, I just let the game run long enough to see the boss, and it was awesome. Also amusing spinning and spewing bullets everywhere, but fun (amusing in a good way!). I'll take a look and see if I can't patch up the code to get him doing closer to what you described.

**Comment by stannardtyler** [comment]
So if I download the new unity update, will it mess up the game when I test it out? Jus curious! Was going to add that today is my last final! So after this i can spend my time on our game and get it into gear and try to get one full level going lol. Anyways i'll check on github and see what issues we got. So far I'm thinking we need some terrain since we have the ships and bullets.Let me know your thoughts here or I'll continue the convo on github!
Hope you guys survived finals lol. 

    On Tuesday, December 20, 2016 2:38 PM, Johnathon Ludeman <notifications@github.com> wrote:
 

 Honestly, I just let the game run long enough to see the boss, and it was awesome. Also amusing spinning and spewing bullets everywhere, but fun (amusing in a good way!). I'll take a look and see if I can't patch up the code to get him doing closer to what you described.—

**Comment by flip40** [comment]
Just a consideration, we need to make sure the background contrasts with bullet colors. Currently we only really have blue, green, and red bullets (tending towards the brighter end of the scale). Just at the moment, the player bullets are near impossible to see. Of course, we also probably need to scale things up, though I think that is on our end to do.

**Comment by stannardtyler** [comment]
good feedback! Yea i took note to make sure the sprites face the same direction, for easy use on your guy's end. and I make sure to take notice to the color palette because I do agree those bullets are tough to see. I think when we first started designing the look of the game, I was looking for more of a "in space" look, like that the combat is all in space. We can have those levels of course but I do like the idea of most levels being on the surface of planets as it will add more dynamics to our parallax style :D. 

I think for now I'll work on levels and when we have it all up in running I look at the art and touch up some things to make them more distinct from the background. Also if you guys have ideas and concepts for a boss character, be it alien or ship let me know! :) I think this is what's gonna be fun!  

    On Tuesday, December 20, 2016 3:15 PM, Johnathon Ludeman <notifications@github.com> wrote:
 

 Just a consideration, we need to make sure the background contrasts with bullet colors. Currently we only really have blue, green, and red bullets (tending towards the brighter end of the scale). Just at the moment, the player bullets are near impossible to see. Of course, we also probably need to scale things up, though I think that is on our end to do.—

**Comment by flip40** [comment]
Just some thoughts looking over the TestAI code, I think the main problem I am seeing is the reliance on timers. Good for some things, depending on what you are going for, but with a lack of any "reset" mechanism, doing things like spinning for an arbitrary amount of time puts the AI in a random rotation that can't be relied on (or, at least, is not being reset to its normal orientation).

One solution is to use more defined actions. For example, instead of using `transform.Rotate(new Vector3 (0, 0, 5));` for 4 seconds, do it and count += 5 until it has rotated through 360 degrees (or however many spins you want). From there it can then swap state and reliably make sense.

A second solution is to make sure the AI resets itself at the end of it's state or before the next begins, whichever makes the most sense (start of state is a bit safer, but some, like spinning can be reasonably done at end of state). To do this requires figuring out how to move / rotate the AI into the correct position and orientation (and not by setting it instantly to the correct orientation and position).

In general though, position should be checked before running states that rely on it (moving up and down in a vertical line, for example). It should have a stage of moving to a position (bottom right corner) before it attempts to begin it's attack (shooting while moving up to top right corner).

**Comment by flip40** [comment]
I have finished updating the boss AI. Not sure it is exactly what you scripted, but I tried to keep the theme of what your code seemed to be going for in each state.

No PR because I was paying absolutely no attention and accidentally made the commit and push on master (and was promptly confused as to where my code went and why there was no new branch on GitHub after my push. Woops!)

**Comment by flip40** [comment]
#143 should close this I think. The only other code issues I found were solved in #144 and #146, both of which are already merged.
