### ISSUE TITLE
Bullet sprites

### ISSUE THREAD

**Issue by flip40** [DemoProductions/shmup#5]
I would note that the bullets.png I added is a Public Domain png, meaning we have author permission to use it. But we might want to use our own, especially if we might want our own effects or look. Also depends on the style we go with.

**Comment by stannardtyler** [comment]
once we get a feel for our style we can discuss if we want lasers or somethin sci fi related or rather ballistic or maybe a mix. Again once we get the style. I've started some sketches for now.

**Comment by stannardtyler** [comment]
I was gona add more sprites later, but for now a sudo basic projectile that can fit every ship I'll send for now. Later ideas of lasers, bombs, mines, homing missiles have been thought about and made add for prototyping.  Sent it ass a sprite animation rather than a gif.

![shipb](https://cloud.githubusercontent.com/assets/15371385/17272496/614b51cc-564c-11e6-81a6-e303a09596e3.png)

**Comment by flip40** [comment]
We seem to be entirely using #6 for all art, so closing this as unnecessary (and unused) for now.
